version: '3'

networks:
  backend:

volumes:
  data:

services:
  conship:
    image: qlstudio/conship:latest
    depends_on:
      - redis
      - postgres
    networks:
      - backend
    ports:
      - '8080:8080'

  redis:
    image: redis:6-alpine
    networks:
      - backend
    # ports:
    #   - '6379:6379'

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: conship
      POSTGRES_USER: conship
      POSTGRES_PASSWORD: conship
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
    # ports:
    #   - '5432:5432'
