[Mode]
# 运行模式
RunMode = "release" # debug:调试 ｜ test:测试 ｜ release:正式

[Http]
# 服务运行配置
Host = "127.0.0.1" # 监听主机
Port = 8080 # 监听配置

[Redis]
# redis 配置
Addr = "127.0.0.1:6379" # 地址
Password = "" # 密码

[Postgres]
# postgrey 配置
Host = "127.0.0.1" # 地址
Port = 5432 # 端口
User = "conship" # 用户名
Password = "conship" # 密码
DBName = "conship" # 数据库

[Limit]
# 访问限制
Limit = 1000 # 每小时 1000 次

[Cors]
# 跨域配置
Enable = true # 是否开启跨域限制

AllowOrigins = ["*"] # 允许列表：* 表示全部允许
AllowMethods = ["GET", "POST", "PUT", "DELETE"] # 允许请求方式
AllowHeaders = [] # 允许特殊请求头
MaxAge = 7200 # 可以缓存的时间