# 运行模式(debug:调试,test:测试,release:正式)
RunMode = "debug"
# 存储模式(file:文件存储,db:数据库存储)
StorageMode = "file"

[HTTP]
# http监听地址
Host = "0.0.0.0"
# http监听端口
Port = 10088
ShutdownTimeout = 30
# 允许的最大内容长度(64M)
MaxContentLength = 67108864
# 允许输出的最大请求日志长度
MaxReqLoggerLength = 1024


[Log]
# 日志级别(-1:debug,0:info 1:warn,2:error,3:panic)
Level = 0


[Root]
# 用户ID
UserID = 9
# 登录用户名
UserName = "root"
# 登录密码
Password = "abc-123"
# 显示名称
RealName = "Admin"

# redis配置信息
[Redis]
# 地址
Addr = "127.0.0.1:6379"
# 密码
Password = ""


# 请求频率限制
[RateLimiter]
# 是否启用
Enable = false
# 每分钟每个用户允许的最大请求数量
Count = 300
# redis数据库(如果存储方式是redis，则指定存储的数据库)
RedisDB = 10

[CORS]
# 是否启用
Enable = false
# 允许跨域请求的域名列表(*表示全部允许)
AllowOrigins = ["*"]
# 允许跨域请求的请求方式列表
AllowMethods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
# 允许客户端与跨域请求一起使用的非简单标头的列表
AllowHeaders = []
# 请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据
AllowCredentials = true
# 可以缓存预检请求结果的时间（以秒为单位）
MaxAge = 7200


[Gorm]
# 是否开启调试模式
Debug = true
# 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
DBType = "postgres"
# 设置连接可以重用的最长时间(单位：秒)
MaxLifetime = 7200
# 设置数据库的最大打开连接数
MaxOpenConns = 150
# 设置空闲连接池中的最大连接数
MaxIdleConns = 50
# 数据库表名前缀
TablePrefix = "g_"
# 是否启用自动映射数据库表结构
EnableAutoMigrate = true


[Postgres]
# 连接地址
Host = "127.0.0.1"
# 连接端口
Port = 5432
# 用户名
User = "conship"
# 密码
Password = "conship"
# 数据库
DBName = "conship"
# SSL模式
SSLMode = "disable"

[Storage]
Directory=./storage