version: '3'

networks:
  backend:

services:
  golang:
    image: golang:1.18-alpine
    environment:
      - GOPROXY=https://goproxy.cn,direct
    volumes:
      - ..:/code
    networks:
      - backend
    ports:
      - '8080:8080'
    stdin_open: true # 允许外部输入

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: conship
      POSTGRES_USER: conship
      POSTGRES_PASSWORD: conship
    networks:
      - backend
    ports:
      - '5432:5432'

  redis:
    image: redis:6-alpine
    networks:
      - backend
    ports:
      - '6379:6379'
