version: "3"
services:
  postgres:
    image: postgres:14-alpine
    #restart: always
    environment:
      POSTGRES_USER: conship
      POSTGRES_PASSWORD: conship
      POSTGRES_DB: conship
    ports:
      - "5432:5432"
    volumes:
      - conship-pgsql-data:/var/lib/postgresql/data:rw

volumes:
  conship-pgsql-data: