version: "3"
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14-alpine
    #restart: always
    environment:
      POSTGRES_DB: conship
      POSTGRES_USER: conship
      POSTGRES_PASSWORD: conship
    ports:
      - "5432:5432"
    volumes:
      - conship-pgsql-data:/var/lib/postgresql/data

volumes:
  conship-pgsql-data:
