FROM golang:1.18-alpine AS build

RUN apk update && apk add --no-cache git

WORKDIR /build
RUN git clone --recurse-submodules https://github.com/QinLiStudio/Conship.git
RUN go build -o main main.go



FROM alpine:latest
LABEL MAINTAINER="https://ql.sylu.edu.cn"

WORKDIR /app
COPY --from=build /build/config/config.toml ./config/config.toml
COPY --from=build /build/main ./main

EXPOSE 8080
ENTRYPOINT ["/main"]