version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: conship
      POSTGRES_USER: conship
      POSTGRES_PASSWORD: conship
    ports:
      - '5432:5432'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
